### ISSUE TITLE
Спроектировать базу данных приложения

### ISSUE THREAD

**Issue by BrilZliaN** [BrilZliaN/paymentgateway#4]
Подзадачи:
* нарисовать базу данных в yEd (или в чем-то подобном), поместить ее в `/documentation`
* написать SQL-код (MySQL 5.7 / 8 - совместимый) для базы данных

**Comment by BrilZliaN** [comment]
Все timestamp, которые подразумевают собой хранение времени создания объекта, должны по-умолчанию при создании быть проинициализированы значением CURRENT_TIMESTAMP

**Comment by DiplomateProgrammer** [comment]
Кажется, все спроектировано.
