### ISSUE TITLE
Сделать операции к каждому endpoint

### ISSUE THREAD

**Issue by BrilZliaN** [BrilZliaN/paymentgateway#5]
Необходимо сделать классы `*Operation` в пакетах `ru.ifmo.practice.gateway.logic.*`, соединить их с классами `*Controller`, подумать над их реализацией (возможно, основываться на промежуточных результатах задачи #4).

**Comment by BrilZliaN** [comment]
Можно опираться на код из задачи #8: коммит b49f8ed42594ff011c005aee727342f7ae718541

**Comment by IvanGusevGit** [comment]
Сделать code review

**Comment by BrilZliaN** [comment]
Еще необходимо написать тесты к классам *Operation, при этом не дергая реальные *DaoAdapter классы (сделать mock)
